evaleev/libint

lib/autoconf/acx_check_gmpxx.m4, src/bin/libint/key.h, src/bin/test_eri/eri.h
Fixes #29. The problem is described at https://gcc.gnu.org/gcc-4.9/porting_to.html, the `<cstddef>` was updated and must be included before `<gmpxx.h>`.
=> Fix a configure error with gcc 4.9

CHANGES, configure.ac, export/MakeRules.export, export/Makefile, export/configure.export, include/libint2.h, include/libint2/cgshell_ordering.h.in, include/libint2/util/generated/libint2_iface.h, include/libint2/util/generated/libint2_params.h, include/libint2/util/generated/libint2_types.h, include/libint2/util/memory.h, src/lib/MakeRules.in
This is just a clean-up of the proposed solution by @mfherbst that avoids relocating the to-be-installed generated headers.
=> fixed include path handling of in-place vs installed headers to fix #72

include/libint2/basis.h.in
By the way: I am not sure whether this library intends to fully follow the convention of the Gaussian folks. 
If yes, than the present code fails to use cartesian d-functions with the basis set ``6-21G``. See the tab  *Pure vs. Cartesian* on http://gaussian.com/basissets/ for details.
In either case: It's not that big an issue, since libint does not ship ``6-21G`` anyway.
=> Update link to reflect new gaussian website layout

CMakeLists.txt, README_CMake.md, cmake/FindStandardMathLibraryC.cmake, cmake/LibintConfig.cmake.in, cmake/autocmake_safeguards.cmake, cmake/autocmake_static_library.cmake, cmake/psi4OptionsTools.cmake, src/CMakeLists.txt, src/bin/libderiv/CMakeLists.txt, src/bin/libint/CMakeLists.txt, src/lib/libderiv/CMakeLists.txt, src/lib/libderiv/LibintderivConfig.cmake.in, src/lib/libint/CMakeLists.txt, src/lib/libint/LibintintConfig.cmake.in
* MAX/OPT/NEW_AM keywords seems to be the greatest divergence between upstream and Psi4 flavors of Libint1. I won't say that the current scheme is the simplest, but it does reproduce again the AM table in README_CMake.
* Seems to build just fine. There were so few changes to the CMake itself that I'm not too worried about extensively re-testing the build.
* All the generated files had "GNU Lesser General", not "GNU General", so that looks good.
* Built it in Psi4 (PR to Psi4 on Libint build changes not yet submitted) just fine.
* No errors in at least the first 200 Psi4 test cases.
So, look this over and see if you like it, please, and let me know anything you'd like changed. No rush to incorporate it – in fact early next week is when I'd probably look to getting all the Libint/Psi4 …
=> Adds alternate CMake build system to v1.

README_CMake.md, lib/autoconf/libtool.m4, src/bin/libderiv/emit_deriv12_managers.c, src/bin/libderiv/emit_deriv1_managers.c
So libint 1.2.0 works great, but, as discussed [here](https://github.com/psi4/psi4/pull/695), it maxes out at `MAX_AM_ERI=6`. (Symptom at AM8 was that the libderiv generator would segfault upon execution.) @andysim kindly fixed it up by moving from stack to heap, so now it's confirmed to work (including passing all Psi4 tests) at AM8.
I'm sorry to PR so soon after 1.2.0. Tagging is up to you – a 1.2.1 would be handy, but Psi4 doesn't need it.
cc @susilehtola
=> higher AM for libint1

src/CMakeLists.txt
DESTDIR=${CMAKE_BINARY_DIR}/stage was prepended to ${CMAKE_MAKE_PROGRAM} install
appearing in all instances of INSTALL_COMMAND
=> Make Libint buildable with Ninja

CITATION
There was a non-ASCII character in CITATION (**“**), which could throw an error in LaTeX if copied and pasted. This PR changes this single character. I also made sure that the end result compiles correctly in LaTeX.
=> corrected typo in CITATION

include/libint2/util/any.h
This PR adds missing using statements and includes such that the header exposes the same symbols irregardless whether the C++ standard library or the fallback implementation are used.
=> Missing using statements and include

CMakeLists.txt, appveyor.yml, src/CMakeLists.txt, src/bin/libderiv/build_libderiv.c, src/bin/libint/CMakeLists.txt, src/bin/libint/build_libint.c
This is part of *Psi4* porting to Windows (psi4/psi4#933):
=> Port to Windows

CMakeLists.txt
This is part of Psi4 porting to Windows (https://github.com/psi4/psi4/issues/933).
=> Fix version in CMake file

doc/progman/progman.tex, export/fortran/fortran_example.F90, export/fortran/libint_f.F90
Dear Eduard,
I added documentation on how to use the new Fortran bindings to the Programmer's Manual. I hope you don't mind that I removed some of the existing documentation, however I left the instructions on how to (possibly) use Libint from older Fortran standards.
The only thing missing regarding documentation would be to mention in the Wiki how to compile the Fortran bindings. Probably you should add the instructions I mentioned in #94:
> After generating a libint library
> 
> ```
> cd libint-2.x.y
> ./configure --enable-fortran FC=... FCFLAGS=...
> make
> make fortran
> make install
> ```
> 
> This compiles a Fortran example in fortran subdirectory and installs the libint_f.mod file in include.
=> Fortran documentation

CMakeLists.txt, cmake/libint.pc.in
A packager wanted this (https://github.com/psi4/psi4/issues/1589) so that a CMake-built libint can be detected by both cmake and libtool downstream buildsystems. The CMake `LibintConfig.cmake` and friends are too involved to be imitated by libtool.
I constructed the `.pc` file by analogy to Libxc https://gitlab.com/libxc/libxc/blob/master/cmake/libxc.pc.in and https://gitlab.com/libxc/libxc/blob/master/build/libxc.pc.in . It builds and looks like the below, but I haven't tried out its consumption in a downstream libtool build.
```
>>> cat install-am4/lib64/pkgconfig/libint.pc 
prefix=/home/psilocaluser/gits/libint/install-am4
exec_prefix=/home/psilocaluser/gits/libint/install-am4
libdir=/home/psilocaluser/gits/libint/install-am4/lib64 …
```
=> add pkgconfig file to cmake build system

CHANGES, bin/travisci_build_linux.sh, doc/progman/progman.tex, export/fortran/libint_f.F90
I noticed that the dimensions of `libint2_build_3eri` were still not correct in the Fortran wrapper, this should finally fix it.
=> Fortran interface: fix dimensions of 3-center ERI function pointer arrays

export/cmake/CMakeLists.txt.export
CMake build of fortran interface seems to be broken in libint v2.6.0, cmake fails with the error message:
```
CMake Error at CMakeLists.txt:346 (target_link_libraries):
Target "libint_f" of type OBJECT_LIBRARY may not be linked into another
target.  One may link only to STATIC or SHARED libraries, or to executables
with the ENABLE_EXPORTS property set.
```
This pr should fix it, I tested with `cmake --build . --target check`.
=> Fix CMake build of Fortran interface

export/cmake/CMakeLists.txt.export
Currently, in the cmake project, only a static library is produced (libint2.a). This library is compiled without setting the position independent code property to `ON`. This prevents the subsequent linking of the library in a shared library. 
I did it in my local repo, but I thought to spread my solution with the project.
In order to do so, I propose to 
a) add the said property (`set_target_property PROPERTIES POSITION_INDEPENDENT_CODE ON`) to the obejct file produced for the `int2` library.
b) produce a shared and a static version of the libraries without increasing the compile time. This is done by compiling an object file `int2_obj` and subsequently creating a `STATIC` `int2_static` and a `SHARED` `int2` target form it. Compile time is thus the same.
Now both versions are available …
=> Produce static (PIC) and shared versions of the int2 library in the cmake project

src/bin/libint/build_libint.cc
In linking against libint2 built with derivatives, Psi4 folks have noticed errors like the below
```
/home/psilocaluser/gits/hrw-quaternary/objdir_dev10_gcc4/stage/include/libint2/engine.impl.h: In member function 'void libint2::Engine::_initialize()':
/home/psilocaluser/gits/hrw-quaternary/objdir_dev10_gcc4/stage/include/libint2/engine.impl.h:627:3: error: 'LIBINT2_MAX_AM_default1' was not declared in this scope
BOOST_PP_LIST_FOR_EACH_PRODUCT(
^
/home/psilocaluser/gits/hrw-quaternary/objdir_dev10_gcc4/stage/include/libint2/engine.impl.h:627:3: note: suggested alternative: 'LIBINT2_MAX_AM_default'
```
We've been patching them up and proceeding (step (5) of https://github.com/psi4/psi4/pull/1721#issuecomment-537945417). This is an attempt at a more permanent solution. It does write the …
=> LIBINT2_MAX_AM_default2 definition

export/fortran/fortran_example.F90
Without this patch, the file doesn't compile with autotools.
=> Fix include file location in fortran_example

src/lib/libint/Makefile.library
Sort input file list
so that `libint2.so.2.0.3` builds in a reproducible way
in spite of indeterministic filesystem readdir order
See https://reproducible-builds.org/ for why this is good.
This patch was done while working on [reproducible builds](https://reproducible-builds.org/) for [openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds).
=> Sort input file list

export/cmake/CMakeLists.txt.export
Make it so find/build targets are the same in exported CMake build. Previously, the build targets were named e.g. `int2` and `cxx` whereas the installed targets were namespaced `Libint2::`. This PR allow for the following
```
cmake_minimum_required( VERSION 3.17 FATAL_ERROR )
project( libint2-as-subproject LANGUAGES CXX )
find_package( Libint2 )
if( NOT Libint2_FOUND )
include( FetchContent )
FetchContent_Declare( libint2
URL https://.......
)
FetchContent_MakeAvailable( libint2 )
endif()
add_executable( my_exe test.cxx )
target_link_libraries( my_exe PUBLIC Libint2::int2 )
```
=> Alias CMake Targets for In-Source Builds

configure, configure.ac
`BOOST_PP_VARIADICS` is introduced in Boost 1.49: https://github.com/boostorg/preprocessor/blob/boost-1.48.0/include/boost/preprocessor/config/config.hpp vs https://github.com/boostorg/preprocessor/blob/boost-1.49.0/include/boost/preprocessor/config/config.hpp#L73-L103
fix #179
=> Bump minimum required Boost version to 1.57 (`BOOST_PP_VARIADICS`)

include/libint2/engine.impl.h, tests/unit/test-2body.cc
added a unit test
resolves #216
=> uniform Cartesian normalization for 2-body ints erroneously used permuted (not original) shell seq

.github/workflows/cmake.yml, CHANGES, bin/take_boostpp_snapshot.sh, include/libint2/basis.h.in, include/libint2/engine.h, include/libint2/engine.impl.h, include/libint2/shell.h, tests/hartree-fock/hartree-fock++.cc, tests/unit/test-precision.cc
standard screening method can significantly overestimate precision of L!=0 integrals (by several orders of magnitude). new "conservative" method overestimates it by must smaller amount. For specific operator type it is also possible to use schwarz bounds to guarantee precision.
=> new primitive screening methods

include/libint2/chemistry/sto3g_atomic_density.h, include/libint2/lcao/1body.h, include/libint2/shell.h, src/bin/libint/exception.h, tests/hartree-fock/hartree-fock++.cc, tests/hartree-fock/hartree-fock.cc
- refactor: use `noexcept` specifier  
`throw` for dynamic exception specification was deprecated
- fix: throw appropriate exceptions
=> improvements related to `throw`

python/CMakeLists.txt
=> update pybind11, confirmed fixes CI Mac

.github/workflows/cmake.yml, INSTALL, export/cmake/CMakeLists.txt.export, include/libint2.h, include/libint2/cxxapi.h, include/libint2/initialize.h, include/libint2/shgshell_ordering.h, include/libint2/solidharmonics.h, include/libint2/util/configuration.h, python/src/libint2/libint2.cc, src/bin/libint/build_libint.cc, src/lib/MakeRules.in, src/lib/libint/configuration.cc.cmake.in
(in order of decreasing importance)
```
libint2::initialize();
libint2::set_solid_harmonics_ordering(libint2::SHGShellOrdering_Gaussian);
``` 
* [added 3 Sept] see https://github.com/evaleev/libint/pull/271/commits/05ff2f12e35dbce950cc1faa586e60367385a05e for testing of the runtime switchable SHO functionality.
* Note that this snapshot has not been tested against Psi4. At the moment, it's the full #259 implementation that I know to be working.
* Now rebased to master. Please squash PR when merging.
=> gss/sss (solid harmonic ordering) runtime switchable

.github/workflows/cmake.yml
Circumvent issue #274, Python 3.12 incompatibility with Libint. The _reason_ for the incompatibility needs to be diagnosed, but this will prevent tests from failing in the meantime.
=> Patch to circumvent #274

tests/hartree-fock/hartree-fock.cc
compute_2body_fock_simple currently contains a memory leak: buf_1324 can be null if all integrals are screened out. I added the same check that is currently being used for buf_1234 to avoid segfaults.
I produced a segfault by running Hartree Fock with compute_2body_fock_simple with sto-3g.
=> Memory leak in simplified fock routine

include/libint2/engine.impl.h, tests/unit/test-1body.cc
Closes #242.
Also adds a test case, using values generated by L2. Attempts to get an independent comparison via Mathematica led to Mathematica not being able to solve the integrals. I could use Obara-Saika to give Mathematica simpler integrals, but at that point, why not trust L2?
=> Fix error in erf/erfc integrals

CHANGES, INSTALL.md
Fix a couple typos and correct `set_solid_harmonics_ordering` advice after new comment in #285 `initialize.h`
=> minor text fixes

include/libint2/diis.h
The 'ngrdiis' variable in the DIIS class was incorrectly initialized. This commit fixes that.
=> fix DIIS initialization

.github/workflows/cmake.yml
seems that some macOS runners have python 3.12 which gets picked up even though we want 3.11 only; this hardwires python paths, but only in the `build_repo` part of the matrix; `build_export` uses Conda python.
=> [ci] hardwire python path in `build_repo`

configure.ac
since `latex2html` is broken on a very common platform (see https://github.com/Homebrew/homebrew-core/issues/25024).
resolves #301
=> disables detection/use of `latex2html` by default

configure.ac, doc/MakeRules.in, doc/MakeVars.in, doc/progman/Makefile
- building of `dvi` targets was broken
- invocation of `latex2html` updated to expected + fixed-up replay of #305 
resolves https://github.com/evaleev/libint/issues/301
=> fixup `dvi` and `html` builds in `progman`

export/cmake/CMakeLists.txt.export
=> Add SONAME/SOVERSION to generated library 

export/cmake/CMakeLists.txt.export, python/CMakeLists.txt
As diagnosed in https://github.com/evaleev/libint/pull/318#issuecomment-1889626192, the latest setuptools doesn't like the empty version present in an independent cmake run of the python project. This mends it, albeit with another hand-sync. pulling out version to an external file would be better, but libtool+cmake already has 2 places to edit version, so I kept the file structure simple and make it 3 places to edit. cmake+cmake is cleaner.
=> fix CI for setuptools=69

.github/workflows/cmake.yml, export/cmake/CMakeLists.txt.export, include/libint2/engine.impl.h, tests/unit/test-permute.cc
=> fix BOOST_PP-related dispatch bug that affects 3-center derivatives when configured with `--with-max-am=X --with-eri3-max-am=Y`

export/cmake/configuration-gen.py, include/libint2/shell.h, src/bin/test_eri/time_eri.cc
I think one `n` is missing, one `l` is missing, and one `p` too many. I checked p13 of https://archive2.iupap.org/wp-content/uploads/2014/05/A4.pdf that you linked over at BSE, and `n` and `l` are present. I'm building an AM=12, but I don't know of any problems associated with this.
=> AM symbols list

src/bin/test_eri/prep_libint2.h
=> narrow down the distribution of cartesian coordinates of shells produced by RandomShellSet

include/libint2/config.h.in, include/libint2/shell.h, src/bin/libint/default_params.cc, src/bin/libint/default_params.h, src/bin/libint/gauss.cc, src/bin/libint/test.cc, src/bin/test_eri/time_eri.cc, tests/eri/test.cc
includes additional fixes/improvements:
- `Shell::am_symbol_to_l` fixed
- am symbols for high l switched from base-10 to base-20 notation ... e.g. instead of `l`, `m`, `ps`, `pp` the new labels  goes as `y`, `z`, `ps`, `pp`, etc.
=> l->symbol maps condensed to 1 definition for non-Python code

CMakeLists.txt, INSTALL.md, cmake/modules/.git_archival.txt, cmake/modules/DynamicVersion.cmake, cmake/modules/int_versions.cmake, include/libint2/util/configuration.h, src/lib/libint/configuration.cc, tests/unit/test.cc
The steps to full cmake replacing #259 aren't going to be nicely separable, so I don't expect this to run on GHA. (EDIT: immediate error is an errant std::string that I'll fix up.) The best I can do is collect changes by topic, so here's the first one focusing on versioning and extra stuff for the configuration.cc file you mentioned in September.
Overall, is this a satisfactory approach? And are there any other items you want accessible in configuration.cc? 
Here's a few outputs for orientation:
```
-- LibintRepository_VERSION  2.8.0
-- LibintRepository_COMMIT   22fa24165540520e05ddc3ab3529498f14bc2061
-- LibintRepository_DISTANCE 0
-- LibintRepository_DESCRIBE v2.8.0
-- LIBINT_GIT_COMMIT         22fa241
-- Version: Full 2.8.0 Numeric 2.8.0 Sortable 2.8.0
-- SO Version: Full 2:3:0 Major 2 …
```
=> full cmake 1/N: git and ref in configuration.cc

configure.ac, src/bin/libint/build_libint.cc
Addresses Issue #236 by enabling access to Cartesian one-body property derivatives.
Acts similarly to the `DISABLE_ONEBODY_PROPERTY_DERIVS` by just skipping formation of the files if SphericalMultipoleOper && deriv_level > 0 is detected.
```
#ifdef DISABLE_ONEBODY_PROPERTY_DERIVS
const auto property_operator =
!(std::is_same<_OperType, OverlapOper>::value ||
std::is_same<_OperType, KineticOper>::value ||
std::is_same<_OperType, ElecPotOper>::value);
if (property_operator && deriv_level > 0) return;
#endif
```
Obviously, the configure.ac file has no effect for when Libint is switched to CMake, but I've changed the build_libint.cc with Lori's branch new-cmake-2023-take2-b with Psi4 before and this works with the change as well.
In response to @loriab  Issue #236, I am able to match Psi4's …
=> Allow access to Cartesian multipole derivatives

include/libint2/util/vector_x86.h
Currently vector traits of `VectorAVXFloat` are not implemented in `include/libint2/include/libint2/util/vector_x86.h`. Instead the generic implementation defined in `./include/libint2/util/type_traits.h` is used such that a small program like
```C++
#include <libint2.h>
#include <stdio.h>
int main()
{
printf("sizeof(libint2::scalar_type) = %lu\n", sizeof(libint2::scalar_type));
return 0;
}
``` 
mistakenly prints out `sizeof(libint2::scalar_type) = 32`. This pull request fixes this.
=> Added vector_traits<simd::VectorAVXFloat> to correctly represent the properties of VectorAVXFloat

include/libint2/lcao/molden.h
Initialization of the `ao_map_` did not check for the special case `l==1` when using pure solid harmonic bases, resulting in an incorrect order of the coefficients corresponding to all p-shells.
This PR solves the issue.
=> Fixes Molden file generation for solid harmonic bases

export/cmake/CMakeLists.txt.export, export/cmake/libint2-config.cmake.in, include/libint2/basis.h.in, include/libint2/lcao/molden.h, include/libint2/util/deprecated.h
it links against `STATIC` library ``libint2-static` if configured with `LIBINT2_BUILD_SHARED_AND_STATIC_LIBS=ON`
`libint2_cxx` now links against `libint2` which is a `SHARED` library
=> [cmake] introduce `libint2_cxx-static`

src/bin/libint/memory.h
Gcc-15 and unreleased clang-21 don't implicitly include it anymore for intptr_t.
https://gcc.gnu.org/gcc-15/porting_to.html#header-dep-changes
Bug: https://bugs.gentoo.org/939020
```
clang++ -O2  -DHAVE_CONFIG_H  -D__COMPILING_LIBINT2=1 -I../../../src/bin -I../../../include -I/home/ask/sources/libint/src/bin/libint/../../../include -I/home/ask/sources/libint/src/bin/libint/../../../src/bin  -I/usr/include -I. -I/home/ask/sources/libint/src/bin/libint  -c -o memory.o memory.cc
In file included from memory.cc:23:
./memory.h:156:11: error: unknown type name 'intptr_t'; did you mean '__intptr_t'?
156 |   typedef intptr_t Address;
|           ^~~~~~~~
|           __intptr_t
/usr/include/bits/types.h:207:25: note: '__intptr_t' declared here
207 | __STD_TYPE __SWORD_TYPE __intptr_t;
| …
```
=> Include implicit cstdint

export/cmake/CMakeLists.txt.export
- The CXX compiler driver is used to link Fortran executables.
- The issue is exposed by, e.g., Intel Fortran Compiler.
- LINKER_LANGUAGE Fortran.
=> CMake: set target properties of Fortran tests
